spring:
  application:
    name: demo
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demo
    platform: h2
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
---
#spring:
#  prifile: des
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo
#    username: root
#    password: root
#  jpa:
#    hibernate.ddl-auto: create
#    generate-ddl: true
#    show-sql: true