spring:
  profileS:
    active: dev

default:
  sender: lukys.taylor@gmail.com
  recipent: lukys.taylor@gmail.com

#miliseconds
jwt:
  secret: CaractererSequence
  expiration: 86400000

#AWS - S3 - Storage
aws:
  access_key_id:
  secret_access_key:
s3:
  bucket: architect-spring
  region: sa-east-1